### PR TITLE
fix bug in Receiver schema

### LINKED ISSUE #153: Schema bug in the `Receiver`
**Bug Description**
Calling the `wrap` function on the wCCD smart contract with `sender != receiver` (The `Receiver` is a smart contract and not an account) fails with the following error `'wrap' in 'CIS2-wCCD-Proxy' at {"index":792,"subindex":0} failed with code -2147483627`

The requested schema is quite weird as follows:

> {
>     "data": "",
>     "to": {
>         "Contract": [
>            {
>                "index": 843,
>                "subindex": 0
>             },
>            {
>                "contract": "auction",
>                "func": "receiveToken"
>            }
>        ]
>    }
> }

Investigation by Emil:
A bug in the schema type for `Receiver` causes this behavior. The Receiver uses `OwnedEntrypointName` but the schema uses `OwnedReceiveName`.

Solution by Emil:
Replacing the `OwnedReceiveName` [here](https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/concordium-cis2/src/lib.rs#L839) with `schema::Type::String(schema::SizeLength::U16)`

The suggested solution was tested on testnet with the `wCCD` token and worked.

**Expected Result**

The `wrap` call should not fail when `Receiver` is a smart contract.

**Actual Result**

The `wrap` call fails when `Receiver` is a smart contract.

### PR DESCRIPTION
**Pull request by DOBEN**
## Purpose

Fix bug in Receiver schema so a smart contract can be passed as a `Receiver` via the schema.

closes #153 

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: concordium-cis2/src/lib.rs [hunk 1]
```diff
@@ -836,7 +836,7 @@ impl schema::SchemaType for Receiver {
                 String::from("Contract"),
                 schema::Fields::Unnamed(vec![
                     ContractAddress::get_type(),
-                    OwnedReceiveName::get_type(),
+                    schema::Type::String(schema::SizeLength::U16),
```
Comment (abizjak) [inline concordium-cis2/src/lib.rs:839]: Perhaps a short comment what the String represents would be helpful in the future. It is also technically not necessary to have U16 for length. U8 should suffice for entrypoint names.

**Review by abizjak — APPROVED** [review]

File: concordium-cis2/src/lib.rs (hunk 1 above)
Comment (abizjak) [reply concordium-cis2/src/lib.rs:839]: I guess changing U16 -> U8 would break parsing, so never mind.

Comment (DOBEN) [reply concordium-cis2/src/lib.rs:840]: added a comment

**Review by abizjak — APPROVED** [review]
