### PR TITLE
Fix invoke_contract_read_only

### LINKED ISSUE #211: Improve invoke_contract_read_only documentation
**Task description**

Explain what the `read_only` part means.

### PR DESCRIPTION
**Pull request by annenkov**
## Purpose

Fix a reference in `invoke_contract_read_only` documentation: `invoke_contract_raw` to `invoke_contract_raw_read_only`.

Closes #211.

### CODE REVIEW

**Review by Bargsteen — APPROVED** [review]

File: concordium-std/src/traits.rs [hunk 1]
```diff
@@ -327,12 +327,12 @@ pub trait HasHost<State>: Sized {
...
     ) -> ReadOnlyCallContractResult<Self::ReturnValueType>;
 
-    /// Like [`invoke_contract_raw`](Self::invoke_contract_raw), except that the
-    /// parameter is automatically serialized. If the parameter already
-    /// implements [`AsRef<[u8]>`](AsRef) or can be equivalently cheaply
-    /// converted to a byte array, then
-    /// [`invoke_contract_raw`](Self::invoke_contract_raw) should be
-    /// used, since it avoids intermediate allocations.
+    /// Like [`invoke_contract_raw_read_only`](Self::
+    /// invoke_contract_raw_read_only), except that the parameter is
```
Comment (abizjak) [inline concordium-std/src/traits.rs:331]: This doesn't work and leads to broken links in the generated documentation.
Screenshot from 2023-01-06 18-27-15


Please be mindful of these issues.
